#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { gunzipSync } from "node:zlib";
import { scoreFrozenV39ExpectedOuts, type FrozenV39FeatureName } from "../server/mlb-full-modular-mechanistic-feature-builder";

type J = Record<string, any>;
type PState={starts:number;bf:number;outs:number;pitches:number;k:number;bb:number;er:number;recent:Array<{outs:number;pitches:number}>};
type OState={games:number;outs:number};
const SEASONS=["2022","2023","2024","2025","2026_YTD"];
const EXPECTED_ROWS:any={"2022":2398,"2023":2399,"2024":2406,"2025":2423,"2026_YTD":1781};
const TOL=1e-12;
const RATE_PRIOR=72,WORK_PRIOR=5,OPP_PRIOR=5,RECENT=5;

function parseArgs(){const a=process.argv.slice(2);const g=(n:string)=>{const i=a.indexOf(n);if(i<0||i+1>=a.length)throw new Error(`MISSING:${n}`);return a[i+1];};return {root:g("--root"),custody:g("--custody"),out:g("--out")};}
function load(p:string){return JSON.parse(readFileSync(p,"utf8"));}
function findFile(root:string,suffix:string){const stack=[root];while(stack.length){const d=stack.pop()!;for(const e of readdirSync(d,{withFileTypes:true})){const p=join(d,e.name);if(e.isDirectory())stack.push(p);else if(p.endsWith(suffix))return p;}}throw new Error(`NOT_FOUND:${suffix}`);}
function pos(v:any){const x=Number(v);return Number.isInteger(x)&&x>0?x:null;}
function finite(v:any){return typeof v==="number"&&Number.isFinite(v);}
function auditValid(a:any){return !!(a&&a.identityOk&&a.sourceHistorical&&a.pregame);}
function probableIds(a:any){if(!auditValid(a)||!a.probableBothKnown)return [null,null] as const;const h=pos(a.homeProbablePitcherId),w=pos(a.awayProbablePitcherId);return h&&w?[h,w] as const:[null,null] as const;}
function lineup(l:any,a:any){if(!auditValid(a)||!l||l.complete!==true)return [null,null] as const;try{const h=(l.homeBattingOrder||[]).map(Number),w=(l.awayBattingOrder||[]).map(Number);if(h.length!==9||w.length!==9||new Set(h).size!==9||new Set(w).size!==9||Math.min(...h,...w)<=0)return [null,null] as const;return [h,w] as const;}catch{return [null,null] as const;}}
function cont(cur:number[]|null,prev:number[]|undefined){if(!cur||!prev)return null;const p=new Set(prev);return cur.filter(x=>p.has(x)).length/9;}
function emptyP():PState{return {starts:0,bf:0,outs:0,pitches:0,k:0,bb:0,er:0,recent:[]};}
function emptyO():OState{return {games:0,outs:0};}
function parseLine(raw:any){const pid=pos(raw?.pitcherId);if(!pid)return null;const map:any={bf:"battersFaced",outs:"outsRecorded",pitches:"numberOfPitches",k:"strikeOuts",bb:"baseOnBalls",er:"earnedRuns"};const z:any={pitcherId:pid};for(const [k,s] of Object.entries(map)){const v=Number(raw?.[s as string]??0);if(!Number.isFinite(v)||v<0)throw new Error(`BAD_STARTER_LINE:${pid}:${s}`);z[k]=v;}return z;}
function addP(s:PState,l:any){s.starts++;for(const k of ["bf","outs","pitches","k","bb","er"] as const)s[k]+=Number(l[k]);s.recent.push({outs:Number(l.outs),pitches:Number(l.pitches)});if(s.recent.length>RECENT)s.recent=s.recent.slice(-RECENT);}
function priors(s:PState){if(s.starts<=0||s.bf<=0)return null;return {outsPerStart:s.outs/s.starts,bfPerStart:s.bf/s.starts,pitchesPerStart:s.pitches/s.starts,kbf:s.k/s.bf,bbbf:s.bb/s.bf,erbf:s.er/s.bf};}
function sr(n:number,d:number,r:number,p:number){return (n+p*r)/(d+p);}
function sm(t:number,n:number,m:number,p:number){return (t+p*m)/(n+p);}
function pfeat(s:PState,p:any):Record<FrozenV39FeatureName,number|null>{const r=s.recent;if(!p)return {pitcher_outs_per_start_shrunk:null,pitcher_bf_per_start_shrunk:null,pitcher_pitches_per_start_shrunk:null,pitcher_kbf_shrunk:null,pitcher_bbbf_shrunk:null,pitcher_erbf_shrunk:null,pitcher_recent5_outs_per_start:null,pitcher_recent5_pitches_per_start:null,opponent_vs_starters_outs_per_game_shrunk:null,opponent_rs10:null,opponent_lineup_continuity:null,pitcher_prior_starts:s.starts};return {pitcher_outs_per_start_shrunk:sm(s.outs,s.starts,p.outsPerStart,WORK_PRIOR),pitcher_bf_per_start_shrunk:sm(s.bf,s.starts,p.bfPerStart,WORK_PRIOR),pitcher_pitches_per_start_shrunk:sm(s.pitches,s.starts,p.pitchesPerStart,WORK_PRIOR),pitcher_kbf_shrunk:sr(s.k,s.bf,p.kbf,RATE_PRIOR),pitcher_bbbf_shrunk:sr(s.bb,s.bf,p.bbbf,RATE_PRIOR),pitcher_erbf_shrunk:sr(s.er,s.bf,p.erbf,RATE_PRIOR),pitcher_recent5_outs_per_start:r.length?r.reduce((a,x)=>a+x.outs,0)/r.length:null,pitcher_recent5_pitches_per_start:r.length?r.reduce((a,x)=>a+x.pitches,0)/r.length:null,opponent_vs_starters_outs_per_game_shrunk:null,opponent_rs10:null,opponent_lineup_continuity:null,pitcher_prior_starts:s.starts};}
function oppRs10(f:any,side:"home"|"away"){const c=Number(f?.combined_team_rs10),d=Number(f?.team_rs10_diff);if(!Number.isFinite(c)||!Number.isFinite(d))return null;const home=(c+d)/2,away=(c-d)/2;return side==="home"?away:home;}

function main(){const args=parseArgs();const custodyRows:J[]=gunzipSync(readFileSync(args.custody)).toString("utf8").split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x));if(custodyRows.length!==11407)throw new Error(`CUSTODY_ROWS:${custodyRows.length}`);const custody=new Map(custodyRows.map(r=>[`${r.season}|${r.gamePk}`,r]));
  let comparisons=0,numeric=0,missing=0,maxDiff=0,eligibleSlots=0,liveProbableSlots=0;const bySeason:any={},examples:any[]=[];
  const cmp=(id:string,field:string,e:any,a:number|null)=>{comparisons++;const x=finite(e)?e:null;if(x===null||a===null){if(x!==a){missing++;if(examples.length<20)examples.push({id,field,expected:x,actual:a,kind:"MISSINGNESS"});}return;}const diff=Math.abs(x-a);maxDiff=Math.max(maxDiff,diff);if(diff>TOL){numeric++;if(examples.length<20)examples.push({id,field,expected:x,actual:a,diff,kind:"NUMERIC"});}};

  for(const season of SEASONS){const base=findFile(args.root,`${season}/game-anatomy-feature-table.json`).replace(/game-anatomy-feature-table\.json$/,"");const canonical=load(join(base,"game-anatomy-feature-table.json"));const sp=load(join(base,"cohort","starting-pitcher-history.json"));const lu=load(join(base,"cohort","pregame-lineup-history.json"));const au=load(join(base,"t5-audit","t5-starter-identity-audit.json"));if(canonical.schemaVersion!=="courtedge-p0-step12v-game-anatomy-feature-table.v1")throw new Error(`BASE_SCHEMA:${season}`);
    const smap=new Map((sp.games||[]).map((x:any)=>[Number(x.gamePk),x]));const lmap=new Map((lu.snapshots||[]).map((x:any)=>[Number(x.gamePk),x]));const amap=new Map((au.rows||[]).map((x:any)=>[Number(x.gamePk),x]));const cr=(canonical.rows||[]).filter((x:any)=>x.t5PregameValid===true);if(cr.length!==EXPECTED_ROWS[season])throw new Error(`ROWS:${season}:${cr.length}`);const byDate=new Map<string,J[]>();for(const r of cr){const d=String(r.officialDate);const z=byDate.get(d)||[];z.push(r);byDate.set(d,z);}
    const ps=new Map<number,PState>(),os=new Map<number,OState>(),league=emptyP(),prev=new Map<number,number[]>();let seasonEligible=0,seasonLiveProbable=0,seasonRows=0;
    for(const date of [...byDate.keys()].sort()){const games=(byDate.get(date)||[]).sort((a,b)=>Number(a.gamePk)-Number(b.gamePk));const pr=priors(league);
      for(const raw of games){seasonRows++;const gp=Number(raw.gamePk),ht=Number(raw.homeTeamId),at=Number(raw.awayTeamId),a=amap.get(gp),[hp,ap]=probableIds(a),[ch,ca]=lineup(lmap.get(gp),a);if(hp&&ap){liveProbableSlots+=2;seasonLiveProbable+=2;}const sg=smap.get(gp),ah=parseLine(sg?.homeStarter),aa=parseLine(sg?.awayStarter),f=raw.features||{},vr=custody.get(`${season}|${gp}`);if(!vr)throw new Error(`V66_ROW_MISSING:${season}:${gp}`);
        for(const [side,pid,actual,opp,oppLu,expectedField] of [["home",hp,ah,at,ca,"home_expected_starter_outs"],["away",ap,aa,ht,ch,"away_expected_starter_outs"]] as const){let pred:number|null=null;if(pid!==null&&actual!==null&&actual.bf>0&&pid===actual.pitcherId){eligibleSlots++;seasonEligible++;const state=ps.get(pid)||emptyP();const p=pfeat(state,pr);const ost=os.get(opp)||emptyO();p.opponent_vs_starters_outs_per_game_shrunk=pr===null?null:sm(ost.outs,ost.games,pr.outsPerStart,OPP_PRIOR);p.opponent_rs10=oppRs10(f,side);p.opponent_lineup_continuity=cont(oppLu as number[]|null,prev.get(opp));pred=scoreFrozenV39ExpectedOuts(p);}cmp(`${season}|${date}|${gp}|${side}`,expectedField,vr[expectedField],pred);}
      }
      for(const raw of games){const gp=Number(raw.gamePk),ht=Number(raw.homeTeamId),at=Number(raw.awayTeamId),sg=smap.get(gp),hl=parseLine(sg?.homeStarter),al=parseLine(sg?.awayStarter);if(hl&&hl.bf>0){const p=ps.get(hl.pitcherId)||emptyP();addP(p,hl);ps.set(hl.pitcherId,p);addP(league,hl);const o=os.get(at)||emptyO();o.games++;o.outs+=hl.outs;os.set(at,o);}if(al&&al.bf>0){const p=ps.get(al.pitcherId)||emptyP();addP(p,al);ps.set(al.pitcherId,p);addP(league,al);const o=os.get(ht)||emptyO();o.games++;o.outs+=al.outs;os.set(ht,o);}const a=amap.get(gp),[ch,ca]=lineup(lmap.get(gp),a);if(ch)prev.set(ht,ch);if(ca)prev.set(at,ca);}
    }
    bySeason[season]={rows:seasonRows,livePregameProbableStarterSlots:seasonLiveProbable,historicalExactProbableRecordedEligibleSlots:seasonEligible};
  }
  const total=numeric+missing;const report={schemaVersion:"courtedge-mlb-router-input-v39-source-parity.v1",classification:total===0?"V39_STEP12V3_SOURCE_TO_V66_PARITY_PASS":"V39_STEP12V3_SOURCE_TO_V66_PARITY_FAIL",authority:{step12v3WorkflowRunId:31659518059,step12v3ArtifactId:9166442982,step12v3ArtifactDigest:"sha256:6d834dfd699dbb9f1ee4b50a557b6613ac0791dff41fadbd5521e189c9fc5f26",v66WorkflowRunId:31962659793,v39ParameterDigest:"sha256:29efa6b950c3dde20e6362cb604341add4df8528ef6d16deadb5f60869d8c0fa"},rows:11407,comparisons,livePregameProbableStarterSlots:liveProbableSlots,historicalExactProbableRecordedEligibleSlots:eligibleSlots,tolerance:TOL,maximumAbsoluteDifference:maxDiff,numericMismatches:numeric,missingnessMismatches:missing,totalMismatches:total,bySeason,historicalReplayUsesRecordedStarterOnlyForEligibilityAudit:true,recordedStarterIdentityIsNotALiveRuntimeFeature:true,seasonHistoryReset:true,sameDateStateUpdateAfterScoring:true,futureGameDataUsed:false,targetGameOutcomeUsedAsModelFeature:false,productionChanged:false,realFinancialExposure:0,mismatchExamples:examples};mkdirSync(dirname(args.out),{recursive:true});writeFileSync(args.out,JSON.stringify(report,null,2)+"\n");console.log("MLB_ROUTER_INPUT_V39_SOURCE_PARITY_REPORT_BEGIN");console.log(JSON.stringify(report));console.log("MLB_ROUTER_INPUT_V39_SOURCE_PARITY_REPORT_END");if(total!==0)throw new Error(`V39_SOURCE_PARITY_FAILED:${total}`);
}
main();
